name: Release (Update PR)

on:
  push:
    branches:
      - develop
      - "releases/**"

jobs:
  update-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get npm Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: "master"
          head-branch-regex: ".*"
          title-template: 🚀リリース@${{ steps.package-version.outputs.current-version}}
          body-template: |
            Merging into '%basebranch%'
            [Link to %headbranch%](https://url/to/browse/ticket/%headbranch%)
          body-update-action: "suffix"
          body-uppercase-base-match: false
