name: Release (Update PR)

on:
  push:
    branches:
      - develop
      - "releases/**"

jobs:
  update_routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get npm Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: 🚀リリース@${{ steps.package-version.outputs.current-version}}
          body: "My pull request body"
          branch: "master"
          commit-message: release@${{ steps.package-version.outputs.current-version}}
          labels: release
