name: Release (Create PR)

on:
  push:
    branches:
      - develop
      - "releases/**"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 🚀Release ${{ github.ref }} into master
          pr_template: ".github/PULL_REQUEST_RELEASE.md"
          pr_label: "release"
