name: Sync to develop

on:
  push:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get npm Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Sync (master 👉 develop)
          pr_template: ".github/PULL_REQUEST_SYNC.md"
